apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: central-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/collinsafa/argo-new.git
    targetRevision: HEAD
    path: argo-deployment
    # kustomize: 
    #   version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true