apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: central-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cafanwi/argocd.git
    targetRevision: HEAD
    path: argo-deployment
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true