apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argo-deployment
  name: argo-deployment
  namespace: argo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}

